### ISSUE TITLE
Incorrect Legality

### ISSUE THREAD

**Issue by MGFlaccid** [AEFeinstein/Mtgjson2Familiar#12]
Mystery Booster exclusive cards are being shown as legal in Commander and Vintage in latest Store update version

**Comment by AEFeinstein** [comment]
OH beta! Yep, I see it now. This is why the beta exists 😀

I'll have to fix this in the patches, which is why I moved the issue here. Please let me know if you come across anything else odd in the beta. Thanks!

**Comment by AEFeinstein** [comment]
FYI @MGFlaccid, you won't see this fixed in the beta. Turns out there was a separate bug in the app-side updater which prevents patching. It's fixed though, I promise. (see https://github.com/AEFeinstein/mtg-familiar/commit/fec72426e0f5b7a65035f09fdce14c67f2770618)
